---

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  tags: hostname

- name: Fix /etc/hosts
  template: src=hosts dest=/etc/hosts
  when: hostname is defined
  tags: hostname

- name: Remove unneeded packages
  apt:
    name:
      - multipath-tools
      - needrestart
      - snapd
      - cloud-init
      - ubuntu-advantage-tools
    state: absent
    purge: yes
    autoremove: yes

- name: Install standard base packages
  apt:
    name:
      - vim
      - iputils-ping
      - open-vm-tools
      - jq
      - fdisk
      - gpg
      - dialog
      - qemu-guest-agent
      - net-tools
      - openvswitch-switch
      - libpve-network-perl 
      - sysstat
      - chrony
      - cpuid
      - rasdaemon
      - numactl
      - numad
      - numatop
    state: present

- name: Update grub defaults
  copy:
    src: grubdefault
    dest: /etc/default/grub
  notify: update-grub
  register: grub

- meta: flush_handlers

- name: Check that eth0 exists
  stat:
    path: /sys/class/net/eth0
  register: eth

- fail:
    msg: "eth0 does not exist, you must reboot the machine and reconfig /etc/network/interfaces"
  when: not eth.stat.exists

- name: Stop rsyslog from dropping privs if it's there
  lineinfile:
    path: /etc/rsyslog.conf
    regex: '^.PrivDropTo'
    state: absent
  tags: rsyslog

- name: Put our /etc/sysctl.d files in place
  copy:
    src: "{{ item }}"
    dest: /etc/sysctl.d/
  with_items:
    - 10-keepalives.conf
    - 60-faster-tcp.conf
  notify: sysctl-reload
  tags:
    - sysctl

- meta: flush_handlers

- name: Create default ssh config
  copy:
    src: sshconfig
    dest: /root/.ssh/config
    force: no
  tags:
    - ssh

- name: Set system start timeout to 60s
  lineinfile:
    path: /etc/systemd/system.conf
    regex: '^#?DefaultTimeoutStartSec='
    line: DefaultTimeoutStartSec=60s
  tags:
    - systemd

- name: Set system stop timeout to 30s
  lineinfile:
    path: /etc/systemd/system.conf
    regex: '^#?DefaultTimeoutStopSec='
    line: DefaultTimeoutStopSec=30s
  tags:
    - systemd

- name: Never hang waiting for network connections
  systemd:
    name: systemd-networkd-wait-online.service
    state: stopped
    enabled: no
    masked: yes
  tags:
    - systemd

- name: Set /tmp to be 0777 instead of 1777
  copy:
    src: tmp-0777.conf
    dest: /etc/tmpfiles.d/
  tags:
    - systemd
    - tmpfiles
  notify:
    - systemd-tmpfiles

- name: Check if resolv.conf is a symlink?
  stat:
    path: /etc/resolv.conf
  register: rconf
  tags:
    - dns

- name: Delete resolv.conf symlink if it exists
  file:
    state: absent
    path: /etc/resolv.conf
  when: rconf.stat.islnk
  tags:
    - dns

- name: Create valid /etc/resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
  tags:
    - dns

# SSH8 disables ssh-rsa keys. Re-enable it.
- name: Allow ssh-rsa in ssh keys
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    insertafter: ^Host
    regexp: 'PubkeyAcceptedKeyTypes '
    line: "    PubkeyAcceptedKeyTypes +ssh-rsa"

- name: Enable agent forwarding
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    insertafter: ^Host
    regexp: 'ForwardAgent '
    line: "    ForwardAgent yes"

- name: VNC Proxy needs all the LC_ variables forwarded
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^AcceptEnv'
    line: "AcceptEnv LANG LC_*"
  notify:
    - restart-sshd

- name: Disable DNS Reverse lookups by sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^UseDNS'
    line: "UseDNS no"
  notify:
    - restart-sshd

- name: ALSO Disable DNS Reverse lookups by sshd
  copy:
    src: etc.default.ssh
    dest: /etc/default/ssh
  notify:
    - restart-sshd

- name: Put chrony config file in place
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
  notify:
    - restart-chrony
  tags:
    - chrony

- name: Make sure chrony is enabled and running
  service:
    name: chrony
    state: started
    enabled: true
  tags:
    - chrony

- name: Autoload msr and cpuid kernel modules
  copy:
    src: rasdaemon.conf
    dest: /etc/modules-load.d/
  notify:
    - loadmodules
  tags:
    - ras

- meta: flush_handlers

- name: Make sure rasdaemon is ready to catch any hardware errors
  service:
    name: rasdaemon
    state: started
    enabled: true

- name: Put 443-8006 remapper script in place
  copy:
    src: fix-port-8006.sh
    dest: /usr/local/bin/fix-port-8006.sh
    mode: 0755
  tags:
    - httpsport


