VIMFIXED=/usr/share/vim/.vimfixed

STARGETS += $(VIMFIXED)

.PHONY: vim
# Comment out (") any lines that enable mouse overrides
vim $(VIMFIXED): /usr/bin/vim
	@sed -i 's/ set mouse=/"set mouse=/' /usr/share/vim/*/defaults*
	@touch $(VIMFIXED)
	@echo Stopped vim from stealing the mouse.



